version: '2'
services:
  nginx: 
    image: nginx:latest
    container_name: production_nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    links:
      - app:app
    ports:
      - 80:80
  postgres:
    environment:
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=hex_app_production
    image: postgres
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - 5431:5432

  redis:
    image: redis
    ports:
      - 6378:6379
    volumes:
      - redis:/data
  app:
    build: 
      context: .
      args:
        secret_token: sometoken
    environment:
      - DB_HOST=postgres
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    command: >
      /bin/bash -c "
        while ! nc -z postgres 5432;
        do
          echo Waiting for PG;
          sleep 1;
        done;
        rm -f /app/tmp/pids/server.pid && rails db:create db:migrate && rails server -b 0.0.0.0"

    depends_on:
      - postgres
      - redis

volumes:
  postgres:
  redis:
  nginx:
