default: &default
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see Rails configuration guide
  # http://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: localhost
  user: docker_user

development:
  <<: *default
  database: hex_app_development

test:
  <<: *default
  database: hex_app_test

production:
  <<: *default
  host: <%= ENV['DB_HOST'] %>
  port: 8081
  database: hex_app_production
  username: postgres
  password: <%= ENV['HEX_APP_DATABASE_PASSWORD'] %>